public with sharing class ItemFestaTriggerHandler extends TriggerHandler {
    
    // private List<Item_Festa__c> newList;
    // private List<Item_Festa__c> oldList;
    // private Map<id, Item_Festa__c> newMap;
    // private Map<id, Item_Festa__c> oldMap;
    
    // public itemFestaTriggerHandler() {
    //     this.newList = (List<Item_Festa__c) Trigger.new;
    //     this.oldList = (List<Item_Festa__c) Trigger.old;
    //     this.newMap = (Map<Item_Festa__c>) Trigger.newMap;
    //     this.oldMap = (Map<Item_Festa__c) Trigger.oldMap;
    // }

    // protect override void beforeUpdate(){
    //     //
    // }

}